
- name: lookup ssm parameter store in nominated region
  hosts: localhost
  connection: local
  tasks:
    - name: create parameter
      community.aws.ssm_parameter:
        name: "Hello"
        value: "Akhila I Love You"
        region: "us-east-1"

    - name: Access variable
      debug: msg="{{ lookup('amazon.aws.aws_ssm', 'test', region='us-east-1' ) }}"