
- name: lookup ssm parameter store in nominated region
  hosts: localhost
  connection: local
  tasks:
    - name: create parameter
      community.aws.ssm_parameter:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        region: "us-east-1"
      loop:
        - {name: "tes2", value: "RAM"}
        - {name: "tes3", value: "chotu"}