
- name: lookup ssm parameter store in nominated region
  hosts: localhost
  connection: local
  tasks:
    - name: create parameter
      community.aws.ssm_parameter:
        name: "Hello"
        value: "world"
        region: "us-east-1"