
- name: lookup ssm parameter store in nominated region
  hosts: all
  connection: local
  tasks:
    - name: lookup ssm parameter store in nominated region
      debug: msg="{{ lookup('aws_ssm', 'test', region='us-east-1' ) }}"