- name: Install Nginix
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent


- name: Create directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name: Unarchive a file
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy config file
  ansible.builtin.copy:
    src: /files/nginx.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Enable service httpd, and not touch the state
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes


