- name: Downloading Repo
  ansible.builtin.shell:
  dnf module disable nodejs
  dnf module enable nodejs:18

- name: Install Nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Useradd
  ansible.builtin.user:
    name: roboshop

- name: Create a directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create a directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Unarchive a file
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
    dest: /app
    remote_src: yes

- name: Install Npm
  community.general.npm:
    path: /app
    state: latest

- name: Daemon reload
  ansible.builtin.systemd:
    name: catalogue
    daemon_reload: true
    enabled: true
    state: started

- name: Install Mongodb
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Load Schema
  ansible.builtin.shell: mongo --host 172.31.47.31 </app/schema/catalogue.js




