- name: Downloading Repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install Nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Useradd
  ansible.builtin.user:
    name: roboshop

- name: Create a directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create a directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Unarchive a file
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
    dest: /app
    remote_src: yes

- name: Install Npm
  community.general.npm:
    path: /app
    state: latest

- name: demon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Enable service
  ansible.builtin.service:
    name: catalogue
    state: started
    enabled: yes

- name: Install Mongodb
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Load Schema
  ansible.builtin.shell: mongo --host 172.31.47.31 </app/schema/catalogue.js




