- name: Declaring variable on playlevel
  hosts: all
  connection: local
  vars:
    URL:play.example.com
  tasks:
    - name: access variable on play level
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: Declare variable on task level
  hosts: all
  connection: local
  tasks:
    - name: access variable on task level
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: play.example.com

- name: Declare variable on file level
  hosts: all
  connection: local
  vars_files:
    - var.yml
  tasks:
    - name: access variable on file level
      ansible.builtin.debug:
        msg: URL == {{URL}}
