- name: Copy config file
  ansible.builtin.copy:
    src: mongo.conf
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongo
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Changing Port adress
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Enable service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes