- name: Add the user Roboshop
  ansible.builtin.user:
    name: roboshop

- name: Remove app
  ansible.builtin.file:
    path: /app
    state: absent

- name: create directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Unarchive a file
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
    dest: /app
    remote_src: yes