- name: Declare variable on playlevel
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: Access variable at play level
      ansible.builtin.debug:
        msg: URL == {{URL}}



- name: Declare variable on task level
  hosts: all
  connection: local
  tasks:
    - name: Access variable on task level
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: TASK.example.com

- name: Declare variable on file
  hosts: all
  connection: local
  vars_files:
    - var.yml
  tasks:
    - name: access variable from file
      ansible.builtin.debug:
        msg: URL == {{URL}}


- name: Access variable from inv
  hosts: all
  connection: local
  tasks:
    - name: Access from INV
      ansible.builtin.debug:
        msg: URL == {{URL}}